hash = {
    "ARTICFL": "ARCTICFLEX",
    "SPEEDDEM": "SPEED DEMON",
    "TRUCKLIT": "TRUCKLITE",
    "REFLECT": "REFLECTOR",
    "INCANDES": "INCANDESCENT",
    "REELCRAF": "REELCRAFT",
    "HENDRICK": "HENDRICKSON",
    "GORMAN R": "GORMAN RUPP",
    "ALLEGHEN": "ALLEGHENY",
    "TEMPERAT": "TEMPERATURE",
    "REPAIRKI": "REPAIR KIT",
    "EMERGENC": "EMERGENCY",
    "FIBERGLA": "FIBER GLASS"

}